[package]
name = "twine-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.11.0", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3.31"
eyre = "0.6"
twine-evm-contracts = { git = "https://github.com/twinexyz/contracts-metadata.git" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
sea-orm = {version = "1.1.4", features = [
        "macros",
        "sqlx-postgres",
        "runtime-tokio-native-tls"
] }
chrono = "0.4.39"
serde = "1.0.217"
axum = "0.8.1"
