[package]
name = "indexer"
edition = "2021"

[dependencies]
evm = { workspace = true }
svm = { workspace = true }
common = { workspace = true }
eyre = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
sea-orm = { workspace = true }
