[package]
name = "indexer"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
common = { workspace = true }
evm = { workspace = true }
eyre = { workspace = true }
sea-orm = { workspace = true }
svm = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
database = {workspace = true}
generic-indexer = {workspace = true}

[dev-dependencies]
pre-commit-hooks = "0.3"
sea-orm-cli = "1.1.7"
