[package]
name = "api"
edition = "2021"

[dependencies]
common = { workspace = true }
api-lib = { workspace = true }
eyre = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
