name: Build and Deploy

on:
  workflow_call:

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  BRANCH: ${{ github.ref_name }}
  REPO: ${{ github.event.repository.name }}
  ORG: ${{ github.repository_owner }}
  ACTIONS_RESULTS_URL: http://10.0.3.106:3000/

jobs:
  build_and_push:
    name: Build Image amd64
    runs-on: self-hosted #ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          #tags: ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }},ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-latest
          tags: ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ github.sha }}
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max
          secrets: |
            github_token=${{ secrets.GH_ACTION_PAT }}
            github_username=${{ github.actor }}
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
      - name: Handle build failure
        if: ${{ failure() }}
        run: echo "Build failed. Check logs for details."

  container-scan:
    needs: ["build_and_push"]
    uses: ./.github/workflows/container-scan.yml
    secrets: inherit

  deploy:
    name: Deploy Latest Tag
    runs-on: self-hosted #ubuntu-24.04
    #if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/dev'
    if: github.ref == 'refs/heads/develop'
    needs: ["build_and_push", "container-scan"]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: twinexyz/argocd
          path: argocd
          token: ${{ secrets.GH_ACTION_PAT  }}
      - name: Update Tag in Helm Values for argocd
        run: |
            ls -al
            cd argocd/apps/values/${{  env.REPO }} &&  sed -i "/tag:/s/tag:.*/tag: ${{ env.BRANCH }}-${GITHUB_SHA}/" staging-api.yaml && sed -i "/tag:/s/tag:.*/tag: ${{ env.BRANCH }}-${GITHUB_SHA}/" staging-indexer.yaml
            git config --global user.email "devops@twinelabs.xyz"
            git config --global user.name "twinebot"
            git add .
            git commit --allow-empty -m "updated image tag to ${GITHUB_SHA} for ${{ env.REPO }}"
            git push origin main
      - name: Handle build failure
        if: ${{ failure() }}
        run: echo "Build failed. Check logs for details."
