name: Build and Deploy

on:
  push:
    branches:
      - '**'  # This will trigger on all branches
    tags:
      - '**'  # This will trigger on all tags
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  BRANCH: ${{ github.ref_name }}
  REPO: ${{ github.event.repository.name }}
  ORG: ${{ github.repository_owner }}

jobs:
  build_and_push:
    name: Build Image amd64
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }},ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-latest
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max
          secrets: |
            github_token=${{ secrets.GH_ACTION_PAT }}
            github_username=${{ github.actor }}
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
      - name: Handle build failure
        if: ${{ failure() }}
        run: echo "Build failed. Check logs for details."

  trivy_scan:
    name: Trivy Docker Image Scan
    runs-on: ubuntu-24.04
    needs: ["build_and_push"]
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PAT }}
      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${GITHUB_SHA}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }}'
          format: 'table'
          ignore-unfixed: true
      - name: Handle build failure
        if: ${{ failure() }}
        run: echo "Build failed. Check logs for details."

  anchore_scan:
    name: Anchore Docker Image Scan
    runs-on: ubuntu-24.04
    needs: ["build_and_push"]
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PAT }}
      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${GITHUB_SHA}
      - name: Scan image
        uses: anchore/scan-action@v6
        with:
          image: 'ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }}'
          fail-build: false
      - name: Handle build failure
        if: ${{ failure() }}
        run: echo "Build failed. Check logs for details."

  docker_scout_scan:
    name: Docker Scout Docker Image Scan
    runs-on: ubuntu-24.04
    needs: ["build_and_push"]
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PAT }}
      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }}
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: quickview,cves,recommendations
          image: ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }}
          ignore-unchanged: true
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.GH_ACTION_PAT }} # to be able to write the comment
      - name: Handle build failure
        if: ${{ failure() }}
        run: echo "Build failed. Check logs for details."

  deploy:
    name: Deploy Latest Tag
    runs-on: ubuntu-24.04
    #if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/dev'
    if: github.ref == 'refs/heads/develop'
    needs: ["build_and_push", "docker_scout_scan", "anchore_scan", "trivy_scan"]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: twinexyz/argocd
          path: argocd
          token: ${{ secrets.GH_ACTION_PAT  }}
      - name: Update Tag in Helm Values for argocd
        run: |
            ls -al
            cd argocd/apps/values/${{  env.REPO }} &&  sed -i "/tag:/s/tag:.*/tag: ${{ env.BRANCH }}-${GITHUB_SHA}/" staging-api.yaml && sed -i "/tag:/s/tag:.*/tag: ${{ env.BRANCH }}-${GITHUB_SHA}/" staging-indexer.yaml
            git config --global user.email "devops@twinelabs.xyz"
            git config --global user.name "twinebot"
            git add .
            git commit --allow-empty -m "updated image tag to ${GITHUB_SHA} for ${{ env.REPO }}"
            git push origin main
      - name: Handle build failure
        if: ${{ failure() }}
        run: echo "Build failed. Check logs for details."
