name: Checks

on:
  push:
    branches:
      - 'develop'  # This will trigger on all branches
    #tags:
    #  - '**'  # This will trigger on all tags

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  BRANCH: ${{ github.ref_name }}
  REPO: ${{ github.event.repository.name }}
  ORG: ${{ github.repository_owner }}

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          git config --global credential.helper store && \
          echo "https://${{github.actor}}:${{ secrets.GH_ACTION_PAT }}@github.com" > ~/.git-credentials && \
          chmod 600 ~/.git-credentials
          cargo test --all-features

  # Check formatting with rustfmt
  formatting:
    name: cargo fmt
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  scan:
    name: scan
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.29.0
      with:
        scan-type: 'fs'
        cache: 'false'
        scan-ref: '.'

    #added for test
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.29.0
      with:
        image-ref: 'ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }}'
        format: 'table'
        ignore-unfixed: true

  build_and_push:
    name: Build Image
    runs-on: ubuntu-24.04
    #if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/dev'
    #needs: ["test", "lint"]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PAT }}

      - name: Build Docker Image
        run: |
          docker build \
          --build-arg GITHUB_TOKEN=${{ secrets.GH_ACTION_PAT }} \
          --build-arg GITHUB_USERNAME=${{github.actor}} \
          -t ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${GITHUB_SHA} \
          .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }}'
          format: 'table'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${GITHUB_SHA}

  deploy:
    name: Deploy Latest Tag
    runs-on: ubuntu-24.04
    #if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/dev'
    if: github.ref == 'refs/heads/develop'
    needs: ["build_and_push"]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: twinexyz/argocd
          path: argocd
          token: ${{ secrets.GH_ACTION_PAT  }}

      - name: Update Tag in Helm Values for argocd
        run: |
            ls -al
            cd argocd/apps/values/${{  env.REPO }} &&  sed -i "/tag:/s/tag:.*/tag: ${{ env.BRANCH }}-${GITHUB_SHA}/" staging-api.yaml && sed -i "/tag:/s/tag:.*/tag: ${{ env.BRANCH }}-${GITHUB_SHA}/" staging-indexer.yaml
            git config --global user.email "devops@twinelabs.xyz"
            git config --global user.name "twinebot"
            git add .
            git commit --allow-empty -m "updated image tag to ${GITHUB_SHA} for ${{ env.REPO }}"
            git push origin main
