name: Checks

on:
  push:
    branches:
      - '**'  # This will trigger on all branches
    tags:
      - '**'  # This will trigger on all tags

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
#  test:
#    name: cargo test
#    runs-on: ubuntu-24.04
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions-rust-lang/setup-rust-toolchain@v1
#      - run: cargo test --all-features
#
#  # Check formatting with rustfmt
#  formatting:
#    name: cargo fmt
#    runs-on: ubuntu-24.04
#    steps:
#      - uses: actions/checkout@v4
#      # Ensure rustfmt is installed and setup problem matcher
#      - uses: actions-rust-lang/setup-rust-toolchain@v1
#        with:
#          components: rustfmt
#      - name: Rustfmt Check
#        uses: actions-rust-lang/rustfmt@v1

  build_and_push:
    name: Build Image
    runs-on: ubuntu-24.04
    #if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/dev'
    #needs: ["test", "lint"]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TWINE_GH_ACTION_PAT }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${GITHUB_REF#refs/heads/}-${GITHUB_SHA} .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${GITHUB_REF#refs/heads/}-${GITHUB_SHA}
