name: Container Scan

on:
  workflow_call:

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  BRANCH: ${{ github.ref_name }}
  REPO: ${{ github.event.repository.name }}
  ORG: ${{ github.repository_owner }}

jobs:
  trivy_scan:
    name: Trivy Docker Image Scan
    runs-on: self-hosted #ubuntu-24.04
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PAT }}
      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }}'
          format: 'table'
          ignore-unfixed: true
      - name: Handle build failure
        if: ${{ failure() }}
        run: echo "Build failed. Check logs for details."

  anchore_scan:
    name: Anchore Docker Image Scan
    runs-on: self-hosted #ubuntu-24.04
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PAT }}
      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }}
      - name: Scan image
        uses: anchore/scan-action@v6
        with:
          image: 'ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ github.sha }}'
          fail-build: false
      - name: Handle build failure
        if: ${{ failure() }}
        run: echo "Build failed. Check logs for details."

  docker_scout_scan:
    name: Docker Scout Docker Image Scan
    runs-on: self-hosted #ubuntu-24.04
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTION_PAT }}
      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ env.BRANCH }}-${{ github.sha }}
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: quickview,cves,recommendations
          image: ghcr.io/${{ env.ORG }}/${{ env.REPO }}:${{ github.sha }}
          ignore-unchanged: true
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.GH_ACTION_PAT }} # to be able to write the comment
      - name: Handle build failure
        if: ${{ failure() }}
        run: echo "Build failed. Check logs for details."
